// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Home → Roles*
 */
export interface HomeDocumentDataRolesItem {
  /**
   * Role field in *Home → Roles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tank, healer, etc
   * - **API ID Path**: home.roles[].role_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role_name: prismic.KeyTextField;

  /**
   * Icon field in *Home → Roles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Lucide icon name (eg. i-lucide-shield)
   * - **API ID Path**: home.roles[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * Status field in *Home → Roles*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: home.roles[].status
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  status: prismic.BooleanField;
}

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ie. above wipe wisdom
   * - **API ID Path**: home.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Roles field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.roles[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  roles: prismic.GroupField<Simplify<HomeDocumentDataRolesItem>>;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type NewsDocumentDataSlicesSlice =
  | ChapterIntroSlice
  | TestimonialSlice
  | ImageCardGridSlice
  | CtaBannerSlice;

/**
 * Content for News documents
 */
interface NewsDocumentData {
  /**
   * Title field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *News*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *News*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: news.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<"Raid" | "News" | "Event" | "Announcement">;

  /**
   * Featured field in *News*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: news.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;

  /**
   * Description field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short Description for News Feed
   * - **API ID Path**: news.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Author field in *News*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Since we don't have users...
   * - **Default Value**: Mali
   * - **API ID Path**: news.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  author: prismic.SelectField<"Mali" | "Qyleth" | "Lasoop", "filled">;

  /**
   * Slice Zone field in *News*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: news.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<NewsDocumentDataSlicesSlice>; /**
   * Meta Title field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: news.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: news.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *News*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * News document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NewsDocumentData>, "news", Lang>;

/**
 * Item in *Streamers → Streamers*
 */
export interface StreamersDocumentDataStreamersItem {
  /**
   * Display Name field in *Streamers → Streamers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: streamers.streamers[].display_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  display_name: prismic.KeyTextField;

  /**
   * Twitch User field in *Streamers → Streamers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: streamers.streamers[].twitch_user
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  twitch_user: prismic.KeyTextField;
}

/**
 * Content for Streamers documents
 */
interface StreamersDocumentData {
  /**
   * Streamers field in *Streamers*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: streamers.streamers[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  streamers: prismic.GroupField<Simplify<StreamersDocumentDataStreamersItem>>;
}

/**
 * Streamers document from Prismic
 *
 * - **API ID**: `streamers`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StreamersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<StreamersDocumentData>,
    "streamers",
    Lang
  >;

export type AllDocumentTypes = HomeDocument | NewsDocument | StreamersDocument;

/**
 * Primary content in *TextCard → Default → Primary*
 */
export interface ChapterIntroSliceDefaultPrimary {
  /**
   * Body field in *TextCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Write your content
   * - **API ID Path**: chapter_intro.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for TextCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default chapter intro variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ChapterIntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ChapterIntroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextCard → TextCard - Highlight → Primary*
 */
export interface ChapterIntroSliceTextCardHighlightPrimary {
  /**
   * Body field in *TextCard → TextCard - Highlight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Write your content
   * - **API ID Path**: chapter_intro.textCardHighlight.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * TextCard - Highlight variation for TextCard Slice
 *
 * - **API ID**: `textCardHighlight`
 * - **Description**: Default chapter intro variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ChapterIntroSliceTextCardHighlight = prismic.SharedSliceVariation<
  "textCardHighlight",
  Simplify<ChapterIntroSliceTextCardHighlightPrimary>,
  never
>;

/**
 * Slice variation for *TextCard*
 */
type ChapterIntroSliceVariation =
  | ChapterIntroSliceDefault
  | ChapterIntroSliceTextCardHighlight;

/**
 * TextCard Shared Slice
 *
 * - **API ID**: `chapter_intro`
 * - **Description**: A chapter introduction section with subtitle, title, and rich text body content
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ChapterIntroSlice = prismic.SharedSlice<
  "chapter_intro",
  ChapterIntroSliceVariation
>;

/**
 * Primary content in *CTA Banner → Default Banner → Primary*
 */
export interface CtaBannerSliceDefaultBannerPrimary {
  /**
   * Heading field in *CTA Banner → Default Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.default_banner.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *CTA Banner → Default Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.default_banner.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button field in *CTA Banner → Default Banner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.default_banner.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default Banner variation for CTA Banner Slice
 *
 * - **API ID**: `default_banner`
 * - **Description**: Default style with heading, description, and a single CTA button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBannerSliceDefaultBanner = prismic.SharedSliceVariation<
  "default_banner",
  Simplify<CtaBannerSliceDefaultBannerPrimary>,
  never
>;

/**
 * Slice variation for *CTA Banner*
 */
type CtaBannerSliceVariation = CtaBannerSliceDefaultBanner;

/**
 * CTA Banner Shared Slice
 *
 * - **API ID**: `cta_banner`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBannerSlice = prismic.SharedSlice<
  "cta_banner",
  CtaBannerSliceVariation
>;

/**
 * Item in *ImageCardGrid → Default → Primary → Cards*
 */
export interface ImageCardGridSliceDefaultPrimaryCardsItem {
  /**
   * Image field in *ImageCardGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_card_grid.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ImageCardGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_card_grid.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *ImageCardGrid → Default → Primary*
 */
export interface ImageCardGridSliceDefaultPrimary {
  /**
   * Cards field in *ImageCardGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_card_grid.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<ImageCardGridSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for ImageCardGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with image cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCardGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageCardGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageCardGrid*
 */
type ImageCardGridSliceVariation = ImageCardGridSliceDefault;

/**
 * ImageCardGrid Shared Slice
 *
 * - **API ID**: `image_card_grid`
 * - **Description**: A grid layout displaying image cards with titles
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCardGridSlice = prismic.SharedSlice<
  "image_card_grid",
  ImageCardGridSliceVariation
>;

/**
 * Primary content in *QuoteCard → Default → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Quote field in *QuoteCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Author Name field in *QuoteCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.author_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Title field in *QuoteCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.author_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_title: prismic.KeyTextField;
}

/**
 * Default variation for QuoteCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default testimonial variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *QuoteCard*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * QuoteCard Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: A testimonial section displaying a quote with author name and title
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataRolesItem,
      HomeDocumentDataSlicesSlice,
      NewsDocument,
      NewsDocumentData,
      NewsDocumentDataSlicesSlice,
      StreamersDocument,
      StreamersDocumentData,
      StreamersDocumentDataStreamersItem,
      AllDocumentTypes,
      ChapterIntroSlice,
      ChapterIntroSliceDefaultPrimary,
      ChapterIntroSliceTextCardHighlightPrimary,
      ChapterIntroSliceVariation,
      ChapterIntroSliceDefault,
      ChapterIntroSliceTextCardHighlight,
      CtaBannerSlice,
      CtaBannerSliceDefaultBannerPrimary,
      CtaBannerSliceVariation,
      CtaBannerSliceDefaultBanner,
      ImageCardGridSlice,
      ImageCardGridSliceDefaultPrimaryCardsItem,
      ImageCardGridSliceDefaultPrimary,
      ImageCardGridSliceVariation,
      ImageCardGridSliceDefault,
      TestimonialSlice,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
    };
  }
}
