/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.output/server/wrangler.json --include-runtime=false` (hash: b87df3e9ab3678d562c6b8da973a6e49)
interface __BaseEnv_Env {
	KV: KVNamespace;
	ASSETS: Fetcher;
	REQUEST_COORDINATOR: DurableObjectNamespace<import("./.output/server/index").RequestCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.output/server/index");
		durableNamespaces: "RequestCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
