/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.output/server/wrangler.json --include-runtime=false` (hash: 5432c80a5eaa35e714fc066e88ac7681)
interface __BaseEnv_Env {
	KV: KVNamespace;
	RECRUITMENT_RATE_LIMITER: RateLimit;
	ROSTER_BUILD_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.output/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
