// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  chapter_intro: defineAsyncComponent(() => import("./TextCard/index.vue")),
  cta_banner: defineAsyncComponent(() => import("./CtaBanner/index.vue")),
  image_card_grid: defineAsyncComponent(
    () => import("./ImageCardGrid/index.vue"),
  ),
  testimonial: defineAsyncComponent(() => import("./QuoteCard/index.vue")),
});
