// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  guild_hero: defineAsyncComponent(() => import("./GuildHero/index.vue")),
  why_choose_us: defineAsyncComponent(() => import("./WhyChooseUs/index.vue")),
});
